# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Ensure output is unbuffered
ENV PYTHONUNBUFFERED 1

# Copy project files
COPY pyproject.toml .
COPY uv.lock .
COPY . .

# Install dependencies and the MCP server
RUN pip install --upgrade pip && \
    pip install . --no-cache-dir

# Default command to run the MCP server over stdio
CMD ["uns_mcp"]
